local cb = peripheral.find("chat_box")

local pp = require "cc.pretty"
local ccstring = require "cc.strings"

local is_emu = not not ccemux

local function help_rps()
    print("Help command received")
end

local rps = require "RPS"

function rps:requestMove(player)
    local other_player = self:otherPlayer(player)
    local player_score = self.scores[player]
    local other_score = self.scores[other_player]

    local move_key_strings

    for key, move in pairs(self.moveset[player]) do
        move_key_strings[move] = string.format("%18.0f", key)
    end

    local score_msg
    if (player_score == other_score) then
        score_msg = "(Tied "..player_score..":"..other_score..")"
    elseif player_score > other_score then
        score_msg = "(Winning "..player_score..":"..other_score..")"
    else
        score_msg = "(Losing "..other_score..":"..player_score..")"
    end

    local message_table = 
    {
        {
            ["text"]="Select your move in your game against "..other_player.."! Score: " .. score_msg .. "\n"
        },
        {
            ["text"]="["..string.upper("rock").."]",
            ["color"]="aqua",
            ["clickEvent"]={
                ["action"]="suggest_command",
                ["value"]="$/rps " .. other_player .. " " .. move_key_strings["rock"]
            }
        },
        {
            ["text"]=" | "
        },
        {
            ["text"]="["..string.upper("paper").."]",
            ["color"]="aqua",
            ["clickEvent"]={
                ["action"]="suggest_command",
                ["value"]="$/rps " .. other_player .. " " .. move_key_strings["paper"]
            }
        },
        {
            ["text"]=" | "
        },
        {
            ["text"]="["..string.upper("scissors").."]",
            ["color"]="aqua",
            ["clickEvent"]={
                ["action"]="suggest_command",
                ["value"]="$/rps " .. other_player .. " " .. move_key_strings["scissors"]
            }
        }
    }
    print(textutils.serializeJSON(message_table))
    cb.sendFormattedMessageToPlayer(textutils.serializeJSON(message_table),player,"PS","R:")
    sleep(.1)
end

-- Rename this to rps_games soon
local games = {}

local function mainLoop()
while true do
    ::continue::
    pp.pretty_print(games)
    local event, sender, message, uuid, isHidden
    if (not is_emu) then
        print("Awaiting new chat")
        event, sender, message, uuid, isHidden = os.pullEvent("chat")
    else
        print("Awaiting new message")
        local h = read(nil,{"tnt,/rps targ rock"})
        print(h)
        sender,message = table.unpack(ccstring.split(h,",",false,2))
        print(sender,message)
    end
    local command = ccstring.split(message,"%s")
    local command_head = string.lower(command[1])
    print(sender,"sent command:")
    pp.pretty_print(command)
    
    -- /rps
    -- >> Could be help, could be "Who do you want to challenge?" with clickables
    -- /rps help|?
    -- >> Displays help.
    -- /rps <target>
    -- >> Generates a chat message for a game with the player chosen.
    -- /rps <target> new <points_to_win>
    -- >> New game command
    -- /rps <target> move <move>
    -- >> Play a move in an existing game. You will not type this. This will be generated by the bot
    if (command_head == "/rps") then
        print("Received RPS command")

        if (#command == 1) then
            help_rps()
        elseif (#command == 2) then
            if (command[2] == "?" or string.lower(command[2]) == "help") then
                help_rps()
            else
                local target = command[2]

                print("Generic from",sender,"to",target)
                    
                -- Validate with Player Detector

                local players = {sender,target}
                table.sort(players)

                local game = games[players[1]] and games[players[1]][players[2]]

                if not game then
                    print("No game found.")
                else
                    print("Game found!")    
                end
            end
        elseif (#command == 4) then
            local target = command[2]

            if (command[3] == "move") then
                print(sender,"is sending a move to",target)
                -- I forsee problems here...
                local move_key = tonumber(command[4])

                local players = {sender,target}
                table.sort(players)
                local game = games[players[1]] and games[players[1]][players[2]]

                if not game then goto continue end

                local move,newKey = game:getMove(sender,move_key)

                if not move then goto continue end

                game:sendMove(sender,move_key)
            elseif (string.lower(command[3]) == "new") then
                local points_to_win = tonumber(command[4])
                print(sender,"is starting a game with",target)

                if not points_to_win then goto continue end

                local players = {sender,target}
                table.sort(players)

                games[players[1]] = games[players[1]] or {}
                games[players[1]][players[2]] = rps:new(sender,target,points_to_win)

                local game = games[players[1]][players[2]]

                pp.pretty_print(game)

                -- send move requests

                game:requestMove(players[1])
                game:requestMove(players[2])
            end
        end
    end
end
end

mainLoop()
